name: Frontend Build

on:
  push:
    branches: 
      - main   # 当代码推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18   # 根据项目需要选择 Node 版本

      # 3. 安装依赖（使用 npm ci 更快）
      - name: Install dependencies
        run: npm ci

      # 4. 构建项目
      - name: Build project
        run: npm run build

      # 5. （可选）将构建产物保存为 artifact
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
