name: Frontend Build

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 打印 Node 和 NPM 版本
      - name: Debug Node & NPM
        run: |
          node -v
          npm -v

      # 3. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 4. 安装依赖 (优先 npm ci，失败则 npm install --include=dev)
      - name: Install dependencies
        run: |
          echo "尝试 npm ci 安装依赖..."
          npm ci || (echo "npm ci 失败，改用 npm install --include=dev" && npm install --include=dev)
          echo "✅ 安装完成"

      # 5. 列出 node_modules 目录确认依赖是否安装成功
      - name: Debug node_modules
        run: |
          ls -la || true
          ls -la node_modules || echo "❌ node_modules 不存在"
          ls -la node_modules/.bin || echo "❌ .bin 不存在"

      # 6. 打印已安装的 vue-cli-service
      - name: Check vue-cli-service
        run: |
          npm list @vue/cli-service || echo "❌ vue-cli-service 未安装"

      # 7. 构建项目
      - name: Build project
        run: npx vue-cli-service build

      # 8. 上传构建产物
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
