name: Frontend Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 打印 Node 和 NPM 版本
      - name: Debug Node & NPM
        run: |
          node -v
          npm -v

      # 3. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 4. 缓存 node_modules
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      # 5. 安装依赖（强制包含 devDependencies）
      - name: Install dependencies
        run: |
          echo "安装依赖（包括 devDependencies）..."
          rm -rf node_modules package-lock.json
          npm install --include=dev --legacy-peer-deps --force

      # 6. 检查 vue-cli-service 是否存在
      - name: Debug vue-cli-service
        run: |
          if [ ! -f "node_modules/.bin/vue-cli-service" ]; then
            echo "❌ vue-cli-service 缺失，尝试手动补链..."
            npm rebuild @vue/cli-service
          fi

          if [ ! -f "node_modules/.bin/vue-cli-service" ]; then
            echo "❌ vue-cli-service 仍不存在，构建失败"
            exit 1
          fi
          echo "✅ vue-cli-service 检查通过"

      # 7. 构建项目
      - name: Build project
        run: npm run build

      # 8. 上传构建产物
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
